# Generated by Django 3.2.9 on 2021-11-19 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redes', '0002_alter_noticia_publicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='conteudo',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='data',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='publicacao',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='titulo',
        ),
    ]
